name: aging
channels:
  - conda-forge
  - bioconda
  - nvidia
  - salilab
  - defaults
dependencies:
  - python>=3.9.0
  - python-devtools
  - setuptools
  - pipx
  - cython
  - boost
  - setuptools>=61.2.0
  - python-dotenv
  - numpy>=1.23.1
  - scipy>=1.9.2
  - scikit-learn
  - scikit-image
  - imbalanced-learn
  - umap-learn
  - einops
  - dask
  - biopython
  - biotite
  - dssp
  - modeller
  - ambertools=23
  - pdbfixer
  - parmed
  - vmd-python
  - nglview
  - openmm
  - mdanalysis
  - MDAnalysisTests
#  - mdachecker
  - maicos
#  - mdaencore
  - mdtraj
  - loos
  - networkx
  - tabulate
  - pandas
  - polars
  - matplotlib>=3.6.2
  - seaborn
  - notebook
  - ipykernel
  - ipython_genutils
  - jupyter_contrib_nbextensions
  - tqdm>=4.64.0
  - ipywidgets
  - jupyterlab
  - ipympl
  - pre-commit
  - black
  - nbstripout
  - requests
  - streamlit
  - streamlit-aggrid
  - osfclient
  - pyyaml
  - mypy
  - flake8
  - pycodestyle
  - pydocstyle
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  - autopep8
  - watermark
  - sphinx
  - sphinx_rtd_theme
  - jq
  - openai
  - nvidia::cuda-driver-dev
  - nvidia::cuda-toolkit
  - nvidia::cuda-libraries
  - nvidia::cuda-libraries-dev
  - nvidia::cuda-tools
  - nvidia::cuda-compiler
  - nvidia::cuda-nvcc
  - nvidia::libcufft-dev
  - nvidia::libcublas-dev
  - nvidia::cuda-python
#prefix: /home/tizio/.miniconda3/envs/namek # read from initialize.sh using the conda -p option
