name: aging
channels:
  - conda-forge
  - bioconda
  - nvidia
  - defaults
dependencies:
  - python>=3.9.0
  - python-devtools
  - setuptools
  - pipx
  - cython
  - setuptools>=61.2.0
  - python-dotenv
  - numpy>=1.23.1
  - scipy>=1.9.2
  - scikit-learn
  - imbalanced-learn
  - biopython
  - biotite
  - ambertools=23
  - parmed
  - openmm
  - mdanalysis
  - MDAnalysisTests
#  - mdachecker
  - maicos
#  - mdaencore
  - mdtraj
  - networkx
  - tabulate
  - pandas
  - pandas-profiling
  - matplotlib>=3.6.2
  - seaborn
  - notebook
  - ipykernel
  - ipython_genutils
  - jupyter_contrib_nbextensions
  - tqdm>=4.64.0
  - ipywidgets
  - jupyterlab
  - ipympl
  - pre-commit
  - black
  - nbstripout
  - requests
  - streamlit
  - streamlit-aggrid
  - osfclient
  - pyyaml
  - mypy
  - flake8
  - pycodestyle
  - pydocstyle
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  - autopep8
  - watermark
  - sphinx
  - sphinx_rtd_theme
  - jq
  - openai
  - nvidia::cuda-driver-dev=12.2
  - nvidia::cuda-toolkit=12.2
  - nvidia::cuda-libraries=12.2
  - nvidia::cuda-libraries-dev=12.2
  - nvidia::cuda-tools=12.2
  - nvidia::cuda-compiler=12.2
  - nvidia::cuda-nvcc=12.2
  - nvidia::libcufft-dev
  - nvidia::libcublas-dev=12.2
  - nvidia::cuda-python=12.2
#prefix: /home/kryohi/.miniconda3/envs/aging # read from initialize.sh using the conda -p option
